### ISSUE TITLE
#bookmarkfolder的笔记在左侧按钮显示消失

### ISSUE THREAD

**Issue by yassita** [JadeVane/Allure#10]
<img width="62" alt="image" src="https://user-images.githubusercontent.com/65555246/188297036-8377e83f-e60d-4a1a-86ef-de4a3b12ec4e.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/65555246/188297049-2eb9d489-7bac-4846-8c62-8d8b02e32fe6.png">
bookmark的图标没问题，folder的就没了

**Comment by JadeVane** [comment]
其他图标显示正常吗，例如内容页底部的操作栏图标

**Comment by ChenSi521** [comment]
都不正常了，只剩几个图标了。

**Comment by JadeVane** [comment]
图标文件更新了，有重新导入新版的图标吗
