### ISSUE TITLE
字体似乎加载失败, 导致icon无法显示

### ISSUE THREAD

**Issue by xgits** [JadeVane/Allure#11]
![image](https://user-images.githubusercontent.com/36815712/190898038-c0090632-d752-4397-90fe-6a49d47c8587.png)
![image](https://user-images.githubusercontent.com/36815712/190898102-66a61e53-e9ee-4394-be0f-f4f91eb4cfbd.png)

**Comment by JadeVane** [comment]
大部分图标都更新过了，如果是从旧版本升级上来的，得重新导入新图标

**Comment by xgits** [comment]
> 大部分图标都更新过了，如果是从旧版本升级上来的，得重新导入新图标

恩! release版本里的文件是好的, 我可能一开始用的文档里的链接, 下载到了不对的font版本. 多谢~
