### ISSUE TITLE
Appreciation Issue

### ISSUE THREAD

**Issue by holmes-py** [JadeVane/Allure#13]
GODDAMN IT 
Thanks a lot for this, the whole theme is so freaking beautiful. I can't thank you enough. Just absolutely brilliant work.

**Comment by JadeVane** [comment]
I'm glad you like the theme. : )

**Comment by FluffMe** [comment]
@JadeVane I concur with my buddy @holmes-py there. Thanks a lot for this.

**Comment by JadeVane** [comment]
@FluffMe My pleasure.

**Comment by JadeVane** [comment]
Since this is not a issue, I closed it, and I updated the theme again, maybe you could have a try, and any ideas are welcome.
