### ISSUE TITLE
No space between icon and description in dropdown menu

### ISSUE THREAD

**Issue by lisp3r** [JadeVane/Allure#14]
![DeepinScreenshot_select-area_20230222173239](https://user-images.githubusercontent.com/6272944/220654838-52516d0b-33b2-4602-b869-807a26af4f62.png)

**Comment by JadeVane** [comment]
Which version of trilium are you using and on which platform

**Comment by lisp3r** [comment]
Trilium version: 0.58.8
OS: arch 6.1.12-arch1-1

**Comment by JadeVane** [comment]
I am sorry that I forgot to reply to this issue, now the new version of the theme is published, whicht adapted to the latest version of trilium and have a better design, welcome to try it out, and any ideas are welcome.

**Comment by JadeVane** [comment]
I've closed this issue given that it was resolved with a version update. Feel free to reopen this issue if it is still not resolved.
