### ISSUE TITLE
Misaligned tab close button and blocks of white background

### ISSUE THREAD

**Issue by sbstratos79** [JadeVane/Allure#15]
Love the theme but it has some major issues that I can't seem to get rid of.
1. Large blocks of white background.
2. Misaligned tab close button

![Screenshot_20230531_120918](https://github.com/JadeVane/Allure/assets/4395586/4511b3b9-4223-4771-8d3b-8b013ecef25d)
![Screenshot_20230531_120928](https://github.com/JadeVane/Allure/assets/4395586/cb999b67-397f-4c32-9274-3c23c53ec67e)

**Comment by JadeVane** [comment]
The problems reflected in the screenshots seem to be more than the ones you described. These problems are basically due to the layout changes after the trilium upgrade. However, Allure did not make timely changes to these upgrades, resulting in misplaced layouts.

These problems are not difficult to solve, but I am upgrading the theme recently, hoping to provide a better experience, so I don’t have time to give priority to solving this problem.

The new version of the theme will be launched recently, and some changes will be made to the current theme. At the same time, it will also solve the problem of adapting the new version that you mentioned in this issue. After the latest version is launched, I can notify you under this issue. If you hope

**Comment by sbstratos79** [comment]
Looking forward to the update. Thanks!

**Comment by JadeVane** [comment]
Sorry to make you wait so long, I've been very busy lately, and the issues I encountered during the development process were more troublesome than I thought.

But anyway, the new version has been updated, try it out, then let me know if you have any ideas

**Comment by sbstratos79** [comment]
Hi. Thanks for your work. But unfortunately, it seems to be even more broken now. :(
![Screenshot_20230823_151716](https://github.com/JadeVane/Allure/assets/4395586/af6e0aec-1f32-4621-8794-e5d2b471bf85)

**Comment by JadeVane** [comment]
Have you upgraded to the latest version of Trilium (0.60.4)?

**Comment by sbstratos79** [comment]
Yes. I am on 0.60.4
![image](https://github.com/JadeVane/Allure/assets/4395586/b73e067a-b801-4e92-a8d4-833d73e8ac5b)

**Comment by JadeVane** [comment]
The icon files have been updated, have you re-imported the new version of the icon files?

In addition, what is the white part on the right, I don't seem to have seen this

**Comment by sbstratos79** [comment]
Updating the icons fixed one of the issues. Thanks!
> In addition, what is the white part on the right, I don't seem to have seen this

It's just a scratchpad widget. I got it from [here](https://github.com/zadam/trilium/discussions/1613#discussioncomment-638984). I don't expect you to fix this since it's a custom widget.

But as you can see in the screenshot, table preview in the "Required Documents" section is completely broken. Is there a way to fix this?

**Comment by JadeVane** [comment]
Fixed.

> It's just a scratchpad widget. I got it from [here](https://github.com/zadam/trilium/discussions/1613#discussioncomment-638984).

By the way,  I like the widget, so I made some simple adaptations to this plugin, and it should work fine now.

Since there are other people who need to use other plugins, I took some time to make a more general adaptation of the plugin, which should make most plugins work

**Comment by JadeVane** [comment]
I've closed this issue given that it was resolved with a version update. Feel free to reopen this issue if it is still not resolved.

**Comment by sbstratos79** [comment]
Hi. I am using the latest version of the theme but there are still some issues. As I mentioned earlier, the table preview in the "Required Documents" section is completely broken. And there is no whitespace between document subheading and paragraph. As you can see in the screenshot, the "Summary" subheading and the lorem ipsum paragraph are joined together. This preview still has a lot of legibility issues.
![Screenshot_20230901_111211](https://github.com/JadeVane/Allure/assets/4395586/85d506e3-7cc9-4bd5-8f6e-d69c76c71b99)

**Comment by JadeVane** [comment]
I don’t know much about Required Documents and have never used this feature, but I tried to make some repairs. You can try to see if the latest version solves your problem.
