### ISSUE TITLE
0.63.5中文版兼容性问题

### ISSUE THREAD

**Issue by EdLiya** [JadeVane/Allure#17]
有两处菜单栏显示空白

<img width="1272" alt="image" src="https://github.com/JadeVane/Allure/assets/15958795/74f91b5a-01bf-4749-add3-9d190376c457">

**Comment by JadeVane** [comment]
我这里测试是正常的，确定图标文件导入没问题吗？

![image](https://github.com/JadeVane/Allure/assets/34258753/43264fa7-1e70-4e38-9cff-9a229ee5344a)

**Comment by EdLiya** [comment]
还是不行，是我笔记安装的时候路径就有问题吗

<img width="1200" alt="image" src="https://github.com/JadeVane/Allure/assets/15958795/531cd3e5-77fb-4f1e-b8b2-7ef6a68d4574">


<img width="1200" alt="image" src="https://github.com/JadeVane/Allure/assets/15958795/e1ab5b46-7f67-4136-9037-d40b1d719d35">

**Comment by EdLiya** [comment]
这个安装路径没问题吧

<img width="731" alt="image" src="https://github.com/JadeVane/Allure/assets/15958795/00661c24-76ce-468b-bc03-6cc20074c492">

<img width="933" alt="image" src="https://github.com/JadeVane/Allure/assets/15958795/38d4ff87-f755-4459-922e-56d6b1675b1f">

**Comment by JadeVane** [comment]
主题跟 Trilium 的安装方式没关系，图标问题里面的 `#customResourceProvider` 应该设置成类似 `#customResourceProvider="Allure-Icons.woff2"` 的格式

如果还是不行，重新 **严格按照 readme 的步骤** 一步步来

**Comment by EdLiya** [comment]
图标设置成功了，果然是引用的问题，我之前都是#customResourceProvider = 用“@”去引用文件，看来这方式不对
