### ISSUE TITLE
TriliumNext 0.90.4 侧边栏图标存在偏移情况

### ISSUE THREAD

**Issue by caiwx86** [JadeVane/Allure#18]
TriliumNext 0.90.4 侧边栏图标存在偏移情况

<img width="1266" alt="1724861416261" src="https://github.com/user-attachments/assets/762815e7-0bb7-451c-ab20-351a8059201e">

**Comment by JadeVane** [comment]
是指菜单按钮吗，这个解决了

**Comment by caiwx86** [comment]
收到 谢谢
