### ISSUE TITLE
trilium 0.46.6 左边栏拉伸时标签不跟随

### ISSUE THREAD

**Issue by iSwiftLiu** [JadeVane/Allure#2]
![image](https://user-images.githubusercontent.com/39252175/115396704-debfee80-a217-11eb-8f95-8cf1c2939ce0.png)

你好，使用了 Auulre-clear 主题，出现如图这个问题

**Comment by JadeVane** [comment]
搜索栏和tab栏无法跟随页面宽度调整，这是已知bug，因为这部分调整单靠CSS无法实现，得上游的trilium解决才行。这个问题已经和作者沟通过了，以后有可能会解决这个问题。
