### ISSUE TITLE
无法在快速搜索结果用键盘上下键选中笔记

### ISSUE THREAD

**Issue by EnBandit** [JadeVane/Allure#21]
首先非常感谢您制作和分享这个简约大方的主题！
我使用了这个主题一段时间，遇到了一个问题：
在原版主题中，快速搜索出现搜索结果后，我可以用键盘上下键选择要跳转的笔记，这个笔记会用灰色标出，按下回车便可跳转
![image](https://github.com/user-attachments/assets/af874ade-9dcf-42ae-bccc-b39c6e145f3b)
但在这个主题里，快速搜索结果中选中的笔记和未选中的笔记在UI上没有区别，只能凭感觉分辨自己用键盘选择了哪个笔记
![image](https://github.com/user-attachments/assets/27c618b3-a982-4486-b2bd-f336cd997479)
另外，与原版主题相比，搜索结果出现的位置似乎也不太对

我尝试自己解决这个问题，但由于对css了解不深，未能解决。希望能得到你的帮助和对这个问题的修复！
再次感谢您创作和分享这个主题！

**Comment by JadeVane** [comment]
之前没用过这个功能，所以没适配，刚更新上去了，而且看着有点丑，所以顺带把界面也适配了。

**注意：更新了图标文件 `Allure-Icons.woff2`，所以此文件需要一起更新**，可以点击图标文件下的 `Upload new version` 按钮更新

![image](https://github.com/user-attachments/assets/5fd8279f-72bb-4650-87f7-c0882dee3903)

另外，搜索弹窗位置不对的问题，我在 `Trilium Next 0.90.4`，`Trilium 0.63.7` 上均未复现，你现在用的是什么版本

**Comment by JadeVane** [comment]
显示位置的问题解决了，更新到最新的试试，这个确实是新版本的问题

另外还有两个问题：

1. 搜索结果中的 "... and 124 more results." 的提示没有了
2. 搜索结果的笔记内容预览有点问题，预览弹窗会显示在搜索结果弹窗的下面

上面两个问题似乎都是新版的 TriliumNext 才有的，不过看样子影响不大，而且修复的话也怕跟其他版本不兼容，所以这两个问题没做修复

另外，感谢捐赠^_^

**Comment by JadeVane** [comment]
还是看着难受，重新研究了下，然后上面说的两个问题也解决了

**Comment by JadeVane** [comment]
能帮上忙就好，一开始放这个主题上来也是希望自己花这么大力气搞出来的东西能多发挥点作用

不用 Trilium 其实也没什么特别的原因，之前 github 上开源的笔记软件我基本都用过，连着几年都在研究哪个笔记软件更好，不够好用的就自己动手改造，直接改源码加功能，当时这个主题就是这么做出来的

但后来发现，记那么多笔记后面能用上的也不多，攒那么多看起来就像只仓鼠，而且哪天真需要用，一个搜索框就够了，能用上关联笔记之类复杂功能的场合太少了，甚至有段时间我纯靠纸记录所思所想，那时候反而觉得思考更清晰了

所以最后还是想从简，记再多笔记不如多思考多复盘，真正想明白的东西才是自己的，所以最后就是想通了而已

**Comment by JadeVane** [comment]
我发现还是有不少人在用这个主题，所以对几个经常用到的菜单做了一次更新，应该会比以前好看，感觉你可能有兴趣

此次更新也需要更新 `Allure-Icons.woff2` 文件

![截图 2024-12-31 15-34-17](https://github.com/user-attachments/assets/fb04df1d-1f63-4fe5-8f0a-ebfea4e80475)
![截图 2024-12-31 15-34-29](https://github.com/user-attachments/assets/816b9b5c-d3c9-4afc-92b8-67f33fdabade)
![截图 2024-12-31 15-34-34](https://github.com/user-attachments/assets/9b46e0b8-324f-4dec-95be-6d76fc27b24f)

**Comment by JadeVane** [comment]
新年快乐！

我之前也想加一个苹方字体来着，不过后来考虑到外国人多、字体文件又很大，所以最后又删掉了

你想加的话，可以先看一下控制台的报错信息，看看字体有没有正确引入，如果没引入的话，会报错说找不到这个字体

css 设置字体其实有不少坑，特别是苹方字体，网上的都是从 Mac 的可变字体里面生成出来的，每个文件对应一个字重，生成的时候很多程序处理不好，渲染时有可能会出问题，报错信息可以在控制台看到

苹方字体基本每个字重都得 11M 左右，可以考虑用 fontmin 缩减字库大小，缩减到常用的 7000 字才 800K，然后自己用的话，normal 和 semibold 两个字重就够了
