### ISSUE TITLE
Missing Scroll bar on TriliumNext 0.91.2-beta

### ISSUE THREAD

**Issue by tanreeve** [JadeVane/Allure#22]
When I update to TriliumNext 0.91.2-beta, the scrollbar is missing in the note, so I can't scroll down the note. However, when I switch to a different theme, such as the TriliumNext Beta (dark) theme, the scrollbar appears and works fine.

**Allure-night Theme:**
![floorp_rvPu6HNSYl](https://github.com/user-attachments/assets/1fd0579e-31b7-4ac9-9caf-8d770a5d8e26)

**TriliumNext Beta (dark) theme :** 
![trilium_M602zg5qv9](https://github.com/user-attachments/assets/ae6a32ac-0d77-431c-85ac-30e5b1ce7ebc)

**Comment by JadeVane** [comment]
I solved it in the latest version, give it a try, and you can continue to give feedback if it doesn't work.

In addition, I felt that the previous menu did not look good enough, so I made some optimizations to several commonly used menus.
![截图 2024-12-31 15-34-17](https://github.com/user-attachments/assets/83019d8a-a6af-424a-9909-c40425897ea9)
![截图 2024-12-31 15-34-29](https://github.com/user-attachments/assets/fdcdcde1-b156-4df1-88e4-151b33ee68aa)
![截图 2024-12-31 15-34-34](https://github.com/user-attachments/assets/7b7768cd-d14b-4697-bb26-1380eb34b92a)

**Comment by JadeVane** [comment]
BTW, `Allure-Icons.woff2` needs to be updated.
