### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by martinkoutecky** [JadeVane/Allure#5]
Hi -- I really like this theme, but if I'm clear neither of your versions displays the icons for notes. It would be very neat to incorporate those!

**Comment by JadeVane** [comment]
Have you download all the fonts in fonts folder and import them to the theme note by right click?

**Comment by martinkoutecky** [comment]
@JadeVane yes - I have also looked in the debugging console and while it is not finding OpenSans, I have tried downloading the icon fonts at the specified URL and it works. Only other thing that looks suspicious (but non-specific) is a 404 on `/libraries/bootstrap/css/bootstrap.min.css`. Other ideas of what could be causing this? Does the theme need to be in some particular place in the note structure, or ... ?

**Comment by JadeVane** [comment]
Do you mean this line that show in devtools

```
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

That's a issue from Trilium, not Allure theme.

**Comment by martinkoutecky** [comment]
@JadeVane yeah, that's what I figured. But why don't I see the icons then?

I also see `GEThttps://t.ef5.cz/custom/fonts/open-sans-v17-latin-600.woff` failing with 404. But that's not the icons font.

**Comment by JadeVane** [comment]
Did you follow all the steps on the readme? for example, the attrs must be set like this, especially the file name marked in the figure

![image](https://user-images.githubusercontent.com/34258753/123357661-8a7d1600-d59c-11eb-8634-1d2b378ed2c9.png)

Font files, such as open sans, do not affect the display of icons.

**Comment by martinkoutecky** [comment]
Yes, I did that. BTW, the readme says the `#customResourceProvider=Allure-Icons.ttf` but the screenshot says `#customResourceProvider=fonts/Allure-Icons.ttf` -- for me it doesn't work with either.

This is using trilium server edition, with firefox. But icons in the white theme work, so I don't suspect the browser.

**Comment by martinkoutecky** [comment]
Hi,
I realized I was inaccurate. I'm seeing icons e.g. for a new note, or even the correct icon for a workspace in the tab (although the tab colors are low contrast -- but that's a different issue). What I'm NOT seeing are icons in the note hierarchy. I attach some examples.

In original dark theme:
![image](https://user-images.githubusercontent.com/445269/123427156-89f87580-d5c4-11eb-9664-37cecd3c8083.png)

In Allure-night-radical:
![image](https://user-images.githubusercontent.com/445269/123427208-9d0b4580-d5c4-11eb-8776-308c82175c6b.png)

Is this intentional? The icons in the tree helped me with navigation.

**Comment by JadeVane** [comment]
Of course, all note type icons have been deliberately deleted, as you can see in readme, so this does not seem to be an issue.

**Comment by martinkoutecky** [comment]
Ah, sorry, I must have overlooked it. This seems too radical to me and it would be really nice if you found some way to put it back in. (After all, Notion also has icons in the hierarchy.) Maybe a reasonable solution would be to not display the default icon but display whenever it differs?

**Comment by JadeVane** [comment]
This is the point I am considering, but now there is no way to implement this change. If necessary, consider providing suggestions to upstream trilium.

**Comment by JadeVane** [comment]
The Allure theme has been updated to the latest version, try to see if there are any problems

**Comment by holmes-py** [comment]
Though I really like the minimal look, I do also really like those icons in the left pane if possible, is there any way to implement a quick patch? Thanks.

**Comment by FluffMe** [comment]
@holmes-py 

Quick patch to get the stock Trilium icons back on the left pane and get the icon picker back -- is to remove the following rule from the theme CSS:
```css
body .note-icon-widget, body .fancytree-custom-icon { display: none; }
```

**Comment by JadeVane** [comment]
I have received several times recently feedback that I would like to bring back the notes icon, which in my opinion is useless except for taking over the display and cluttering up the view, so I have insisted that it be hidden.
Initially I developed this theme just to make it easier for myself to use trilium, but now I realize that this is a public product that gets a lot of attention and has a lot of users, so I should give due consideration to the needs of more people, and in any case, this idea, which has been mentioned many times, should be accepted.
You can get what you want in the latest version of Alure theme.

**Comment by FluffMe** [comment]
@JadeVane Thank you very much for the change!
Maybe we can make it var dependant or ship several CSS for those who prefer cleaner, icon-less look.

**Comment by JadeVane** [comment]
More versions means more dispersion of effort and greater user selection costs, so multiple versions will not be considered for support now.
