### ISSUE TITLE
Contrast is off for tabs in workspaces

### ISSUE THREAD

**Issue by martinkoutecky** [JadeVane/Allure#6]
The background / foreground contrast is very low for tabs. Compare:

original dark theme (good):
![image](https://user-images.githubusercontent.com/445269/123427407-de035a00-d5c4-11eb-8931-8d150f7f3d9a.png)

original white theme (already bad):
![image](https://user-images.githubusercontent.com/445269/123427457-f2dfed80-d5c4-11eb-964d-63ca232920c4.png)

allure-night-radical:
![image](https://user-images.githubusercontent.com/445269/123427528-068b5400-d5c5-11eb-8458-164506f19b47.png)

I would expect that colors I have set for the dark theme maybe won't work for the white theme (this is an issue in trilium, not your theme) BUT I would expect that colors I've set for the original dark theme would work in allure-night.

**Comment by JadeVane** [comment]
Which version of trilium is this, the latest version may not be adapted yet.

**Comment by martinkoutecky** [comment]
Latest - 0.47.4. Desktop.

**Comment by JadeVane** [comment]
The Allure theme has been updated to the latest version, try to see if there are any problems
