### ISSUE TITLE
文章工具条的问题。

### ISSUE THREAD

**Issue by QingShui23** [JadeVane/Allure#7]
如果文章比较长的话，文章工具栏不能出现在正确的位置，他会自动跑到最上面去。
如图：
![Snipaste_2021-11-23_15-13-16](https://user-images.githubusercontent.com/7929884/142983604-a4ebc06e-2c86-4f98-9d62-570423fa2e82.png)

**Comment by JadeVane** [comment]
一直没找到调试这个鼠标事件的方法，所以没得改。。。
