### ISSUE TITLE
菜单栏的icon消失

### ISSUE THREAD

**Issue by moqy22** [JadeVane/Allure#8]
您好！按照指示安装以后，菜单栏上所有的图标消失了
我是在mac os 上安装的，不知道有没有兼容性问题？
![0d280afe5856f300e218e838b625521](https://user-images.githubusercontent.com/56383471/183243512-5bd83598-b527-4c6d-96cc-92c8c4546e5e.jpg)
您的主题
![ea285ca8ea89746c31722d9cc3a4c93](https://user-images.githubusercontent.com/56383471/183243525-056cb6c7-99e1-4690-a0ac-77fd54ea6b1a.jpg)
默认主题
左边那个表示展开和收起的小箭头也消失了

非常感谢您的工作！这个主题超级好看！

**Comment by JadeVane** [comment]
里面的图标是自定义的，要按照readme里面的步骤导入图标文件才能正确显示图标

> 4. 下载 [fonts](https://github.com/JadeVane/Allure/blob/main/fonts) 里面的全部字体，然后在主题笔记右键，选择 Import to note 导入全部字体
> 5. 为每个字体添加 #customResourceProvider="字体名称.字体文件后缀" 属性

**Comment by moqy22** [comment]
谢谢！是写代码的时候出了问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JadeVane ***@***.***>
发送时间: Saturday, August 6, 2022 7:09:37 PM
收件人: JadeVane/Allure ***@***.***>
抄送: moqy22 ***@***.***>; Author ***@***.***>
主题: Re: [JadeVane/Allure] 菜单栏的icon消失 (Issue #8)


里面的图标是自定义的，要按照readme里面的步骤导入图标文件才能正确显示图标

  1.  下载 fonts<https://github.com/JadeVane/Allure/blob/main/fonts> 里面的全部字体，然后在主题笔记右键，选择 Import to note 导入全部字体
  2.  为每个字体添加 #customResourceProvider="字体名称.字体文件后缀" 属性

―

**Comment by JadeVane** [comment]
我就先关掉了，有问题可以再打开

顺带一提，新版本已更新，欢迎试用
