### ISSUE TITLE
分享一条笔记时不显示笔记链接，鼠标拖动选择属性时打开的笔记会滚动

### ISSUE THREAD

**Issue by iSwiftLiu** [JadeVane/Allure#9]
感谢作者开发这么好看的主题，看到主题更新了立刻换上，遇到了几个操作有点问题的地方。
不显示笔记链接
![image](https://user-images.githubusercontent.com/39252175/183949510-01bd0aa7-e9dd-4346-8235-cc57c4477a3d.png)
![image](https://user-images.githubusercontent.com/39252175/183949658-041cd5e1-a363-473d-8759-a91ea0c52e15.png)

鼠标拖动选择属性时打开的笔记会滚动
![image](https://user-images.githubusercontent.com/39252175/183949823-604cb0ad-2cb7-4906-8d36-24b5bfeb1229.png)
下面这一排鼠标移动上去的时候可以像默认主题一样显示提示文字不

**Comment by JadeVane** [comment]
笔记链接和按钮提示的问题已修复

选择属性导致内容滚动是个已知bug，这是改动了布局导致的，暂时没想到怎么解决

**Comment by JadeVane** [comment]
再研究了一番，解决了选择属性导致内容滚动的问题
